// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5DO2cRlFrvucPt-7Uu6t-dukscQ-QHcs',
    appId: '1:960123738627:web:1a28f4b899eaeccd368c36',
    messagingSenderId: '960123738627',
    projectId: 'my-com-cool-message-me-app',
    authDomain: 'my-com-cool-message-me-app.firebaseapp.com',
    storageBucket: 'my-com-cool-message-me-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9kIai9MlWxAQfZAsxK3eh6PAJe9I6sdE',
    appId: '1:960123738627:android:a85b32f8cc1d128a368c36',
    messagingSenderId: '960123738627',
    projectId: 'my-com-cool-message-me-app',
    storageBucket: 'my-com-cool-message-me-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCokWMZv0U7_5sYySPzoFymk3sdhUM1M-k',
    appId: '1:960123738627:ios:969c66daa5da7bcd368c36',
    messagingSenderId: '960123738627',
    projectId: 'my-com-cool-message-me-app',
    storageBucket: 'my-com-cool-message-me-app.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCokWMZv0U7_5sYySPzoFymk3sdhUM1M-k',
    appId: '1:960123738627:ios:79d88b525b3787eb368c36',
    messagingSenderId: '960123738627',
    projectId: 'my-com-cool-message-me-app',
    storageBucket: 'my-com-cool-message-me-app.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
